// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbyswnjzkhxzgslpqlfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRieXN3bmp6a2h4emdzbHBxbGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNjg5NDEsImV4cCI6MjA1MTY0NDk0MX0.GkCKMH_AkHXJUNzmLJrU0bjmaGA6orHv9S7P1Dt33zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);